function PluginInterface = GeneratePluginInterface(vendorVersion, pluginType)
% GENERATEPLUGININTERFACE Check the MATLAB version and generate an
% appropriate audioPluginInterface object to be used in building a plugin
%
%   vendorVersion (required) - a string with the plugin version (ex: '1.0.0')
%   lite          (optional) - flag to create full or lite GUI (ex: true)
%
%   In MATLAB 2019b the Audio Toolbox features new, advanced GUI options.
%   This provides a means to make more complex GUIs with custom placement
%   of different kinds of UI elements. To take advantage of this feature,
%   while also provide backwards compatability (2019b is still in prelease
%   at this time), this function allows for audioPluginInterface objects to
%   be generated dynamically based on the current MATLAB version and
%   whether you are building the full plugin or the lite version.
%

if ~exist('pluginType', 'var')
    pluginType = 'full';
end

% check if supplied vendor version is valid string

% get current MATLAB version number
fv = split(version);
vnum = cellfun(@str2num,split(fv{1}, '.'));

% Use fancy custom GUI elements if on 2019b or above
if (vnum(1) == 9 && vnum(2) >= 7)
    
    if strcmp(pluginType, 'lite')
        
        PluginInterface = audioPluginInterface(...
            'InputChannels',2,...
            'OutputChannels',2,...
            'PluginName','flowEQ-lite',...
            'VendorName','Christian Steinmetz',...
            'VendorVersion','0.9.0',...
            ... % GUI Configuration
            audioPluginGridLayout('RowHeight',[30 30 30 30 30 30],...
                                  'ColumnWidth',[40 40 5 40 40 40 40 40 50 50],...
                                  'RowSpacing',15,...
                                  'ColumnSpacing',15,...
                                  'Padding',[20 20 20 20]),...
            ...%'BackgroundColor',[19/255, 22/255, 26/255],...
            ... % Model Parameters
            audioPluginParameter('xDim',            'DisplayName','x',           'Label','',   'Mapping',{'lin', -2, 2},        'Layout',[1,5; 1,10],  'DisplayNameLocation', 'left', 'EditBoxLocation', 'right'),...
            audioPluginParameter('yDim',            'DisplayName','y',           'Label','',   'Mapping',{'lin', -2, 2},        'Layout',[2,5; 2,10],  'DisplayNameLocation', 'left', 'EditBoxLocation', 'right'),...
            audioPluginParameter('zDim',            'DisplayName','z',           'Label','',   'Mapping',{'lin', -2, 2},        'Layout',[3,5; 3,10],  'DisplayNameLocation', 'left', 'EditBoxLocation', 'right'),...
            audioPluginParameter('extend',          'DisplayName','Extend (x2)', 'Label','',   'Mapping',{'enum', 'Off', 'On'}, 'Layout',[4,9; 5,10],   'DisplayNameLocation', 'below', 'Style', 'vtoggle'),...
            audioPluginParameter('strength',        'DisplayName','Strength',    'Label','',   'Mapping',{'lin', 0, 1},         'Layout',[4,7; 5,8],   'DisplayNameLocation', 'below', 'Style', 'rotaryknob'),...           
            audioPluginParameter('gainCompensation','DisplayName','Auto Gain',   'Label','',   'Mapping',{'enum', 'Off', 'On'}, 'Layout',[4,4; 5,5],   'DisplayNameLocation', 'below', 'Style', 'vtoggle'),...          
            audioPluginParameter('inputGain',       'DisplayName','In Gain',     'Label','dB', 'Mapping',{'pow', 1/3, -80, 12}, 'Layout',[1,1; 2,2],   'DisplayNameLocation', 'below', 'Style', 'rotaryknob'),...
            audioPluginParameter('outputGain',      'DisplayName','Out Gain',    'Label','dB', 'Mapping',{'pow', 1/3, -80, 12}, 'Layout',[4,1; 5,2],   'DisplayNameLocation', 'below', 'Style', 'rotaryknob'));
        
    else
        
        PluginInterface = audioPluginInterface(...
            'InputChannels',2,...
            'OutputChannels',2,...
            'PluginName','flowEQ',...
            'VendorName','Christian Steinmetz',...
            'VendorVersion',vendorVersion,...
            ... % GUI Configuration
            audioPluginGridLayout('RowHeight',[25 25 25 25 25 25 25 25 25 60 25 60 25 60 25],...
                                  'ColumnWidth',[70 70 60 100 100 100 100 100],...
                                  'RowSpacing',15,...
                                  'ColumnSpacing',15,...
                                  'Padding',[20 20 20 20]),...
            ...%'BackgroundColor',[19/255, 22/255, 26/255],...
            ... % Model Parameters
            audioPluginParameter('latentDim',       'DisplayName','Latent',            'Label','',   'Mapping',{'enum','1','2','3'},                      'Layout',[6,5; 6,5],   'DisplayNameLocation', 'left'),...
            audioPluginParameter('eqMode',          'DisplayName','EQ Mode',           'Label','',   'Mapping',{'enum', 'Traverse','Semantic','Manual'},  'Layout',[1,5; 1,8],   'DisplayNameLocation', 'left'),...
            audioPluginParameter('xDim',            'DisplayName','x',                 'Label','',   'Mapping',{'lin', -2, 2},                            'Layout',[2,4; 2,5],   'DisplayNameLocation', 'left', 'EditBoxLocation', 'right'),...
            audioPluginParameter('yDim',            'DisplayName','y',                 'Label','',   'Mapping',{'lin', -2, 2},                            'Layout',[3,4; 3,5],   'DisplayNameLocation', 'left', 'EditBoxLocation', 'right'),...
            audioPluginParameter('zDim',            'DisplayName','z',                 'Label','',   'Mapping',{'lin', -2, 2},                            'Layout',[4,4; 4,5],   'DisplayNameLocation', 'left', 'EditBoxLocation', 'right'),...
            audioPluginParameter('extend',          'DisplayName','Extend (x2)',       'Label','',   'Mapping',{'enum', 'Off', 'On'},                     'Layout',[5,5; 5,5],   'DisplayNameLocation', 'left'),...
            audioPluginParameter('firstCode',       'DisplayName','Embedding A',       'Label','',   'Mapping',{'enum', 'Warm','Warmer','Warmest','Bright','Brighter','Brightest'},'Layout',[2,7; 2,8],   'DisplayNameLocation', 'left'),...
            audioPluginParameter('secondCode',      'DisplayName','Embedding B',       'Label','',   'Mapping',{'enum', 'Warm','Warmer','Warmest','Bright','Brighter','Brightest'},'Layout',[3,7; 3,8],   'DisplayNameLocation', 'left'),...
            audioPluginParameter('interpolate',     'DisplayName','Interpolate',       'Label','',   'Mapping',{'lin', 0, 1},                             'Layout',[4,7; 4,8],   'DisplayNameLocation', 'left', 'EditBoxLocation', 'right'),...
            audioPluginParameter('disentanglement', 'DisplayName','Beta',              'Label','',   'Mapping',{'enum', 'None','Less', 'Some', 'More'},   'Layout',[6,7; 6,7],   'DisplayNameLocation', 'left'),...
            audioPluginParameter('strength',        'DisplayName','Strength',          'Label','',   'Mapping',{'lin', 0, 1},                             'Layout',[7,5; 7,8],   'DisplayNameLocation', 'left', 'EditBoxLocation', 'right'),...           
            audioPluginParameter('gainUpdateRate',  'DisplayName','Update Rate',       'Label','',   'Mapping',{'enum', 'Fast','Med.','Slow'},            'Layout',[11,2; 11,2], 'DisplayNameLocation', 'below', 'Style', 'dropdown'),...          
            audioPluginParameter('gainRange',       'DisplayName','Gain Range',        'Label','',   'Mapping',{'enum', '6dB','12dB','24dB'},             'Layout',[11,1; 11,1], 'DisplayNameLocation', 'below', 'Style', 'dropdown'),...          
            audioPluginParameter('gainCompensation','DisplayName','Auto Gain Comp.',   'Label','',   'Mapping',{'enum', 'Off', 'On'},                     'Layout',[10,1; 10,1], 'DisplayNameLocation', 'right', 'Style', 'checkbox'),...          
            audioPluginParameter('inputGain',       'DisplayName','In Gain',           'Label','dB', 'Mapping',{'pow', 1/3, -80, 12},                     'Layout',[1,1; 8,1],   'DisplayNameLocation', 'below', 'Style', 'vslider'),...
            audioPluginParameter('outputGain',      'DisplayName','Out Gain',          'Label','dB', 'Mapping',{'pow', 1/3, -80, 12},                     'Layout',[1,2; 8,2],   'DisplayNameLocation', 'below', 'Style', 'vslider'),...
            ... % Parametric EQ Parameters 
            audioPluginParameter('lowShelfActive',  'DisplayName','Active',            'Label','',   'Mapping',{'enum', 'Bypassed','Active'},             'Layout',[9,4; 9,4],   'DisplayNameLocation', 'none',  'Style', 'checkbox'),...
            audioPluginParameter('lowShelfGain',    'DisplayName','Lowshelf Gain',     'Label','dB', 'Mapping',{'lin', -12, 12},                          'Layout',[10,4; 10,4], 'DisplayNameLocation', 'below', 'Style', 'rotaryknob'),...
            audioPluginParameter('lowShelfFreq',    'DisplayName','Lowshelf Freq.',    'Label','Hz', 'Mapping',{'lin', 22, 1000},                         'Layout',[12,4; 12,4], 'DisplayNameLocation', 'below', 'Style', 'rotaryknob'),...
            audioPluginParameter('firstBandActive', 'DisplayName','Active',            'Label','',   'Mapping',{'enum', 'Bypassed','Active'},             'Layout',[9,5; 9,5],   'DisplayNameLocation', 'none',  'Style', 'checkbox'),...
            audioPluginParameter('firstBandGain',   'DisplayName','First Band Gain',   'Label','dB', 'Mapping',{'lin', -12, 12},                          'Layout',[10,5; 10,5], 'DisplayNameLocation', 'below', 'Style', 'rotaryknob'),...
            audioPluginParameter('firstBandFreq',   'DisplayName','First Band Freq.',  'Label','Hz', 'Mapping',{'lin', 82, 3900},                         'Layout',[12,5; 12,5], 'DisplayNameLocation', 'below', 'Style', 'rotaryknob'),...
            audioPluginParameter('firstBandQ',      'DisplayName','First Band Q',      'Label','',   'Mapping',{'lin', 0.1, 10},                          'Layout',[14,5; 14,5], 'DisplayNameLocation', 'below', 'Style', 'rotaryknob'),...
            audioPluginParameter('secondBandActive','DisplayName','Active',            'Label','',   'Mapping',{'enum', 'Bypassed','Active'},             'Layout',[9,6; 9,6],   'DisplayNameLocation', 'none',  'Style', 'checkbox'),...
            audioPluginParameter('secondBandGain',  'DisplayName','Second Band Gain',  'Label','dB', 'Mapping',{'lin', -12, 12},                          'Layout',[10,6; 10,6], 'DisplayNameLocation', 'below', 'Style', 'rotaryknob'),...
            audioPluginParameter('secondBandFreq',  'DisplayName','Second Band Freq.', 'Label','Hz', 'Mapping',{'lin', 180, 4700},                        'Layout',[12,6; 12,6], 'DisplayNameLocation', 'below', 'Style', 'rotaryknob'),...
            audioPluginParameter('secondBandQ',     'DisplayName','Second Band Q',     'Label','',   'Mapping',{'lin', 0.1, 10},                          'Layout',[14,6; 14,6], 'DisplayNameLocation', 'below', 'Style', 'rotaryknob'),...
            audioPluginParameter('thirdBandActive', 'DisplayName','Active',            'Label','',   'Mapping',{'enum', 'Bypassed','Active'},             'Layout',[9,7; 9,7],   'DisplayNameLocation', 'none',  'Style', 'checkbox'),...
            audioPluginParameter('thirdBandGain',   'DisplayName','Third Band Gain',   'Label','dB', 'Mapping',{'lin', -12, 12},                          'Layout',[10,7; 10,7], 'DisplayNameLocation', 'below', 'Style', 'rotaryknob'),...
            audioPluginParameter('thirdBandFreq',   'DisplayName','Third Band Freq.',  'Label','Hz', 'Mapping',{'lin', 220, 10000},                       'Layout',[12,7; 12,7], 'DisplayNameLocation', 'below', 'Style', 'rotaryknob'),...
            audioPluginParameter('thirdBandQ',      'DisplayName','Third Band Q',      'Label','',   'Mapping',{'lin', 0.1, 10},                          'Layout',[14,7; 14,7], 'DisplayNameLocation', 'below', 'Style', 'rotaryknob'),...
            audioPluginParameter('highShelfActive', 'DisplayName','Active',            'Label','',   'Mapping',{'enum', 'Bypassed','Active'},             'Layout',[9,8; 9,8],   'DisplayNameLocation', 'none',  'Style', 'checkbox'),...
            audioPluginParameter('highShelfGain',   'DisplayName','Highshelf Gain',    'Label','dB', 'Mapping',{'lin', -12, 12},                          'Layout',[10,8; 10,8], 'DisplayNameLocation', 'below', 'Style', 'rotaryknob'),... 
            audioPluginParameter('highShelfFreq',   'DisplayName','Highshelf Freq.',   'Label','Hz', 'Mapping',{'lin', 580, 20000},                       'Layout',[12,8; 12,8], 'DisplayNameLocation', 'below', 'Style', 'rotaryknob')); 
    end
    
% Use standard GUI elements if on older version
else

    if strcmp(pluginType, 'lite')
        
         PluginInterface = audioPluginInterface(...
            'InputChannels',2,...
            'OutputChannels',2,...
            'PluginName','flowEQ-lite',...
            'VendorName','Christian Steinmetz',...
            'VendorVersion',vendorVersion,...
            ... % Model Parameters
            audioPluginParameter('xDim',            'DisplayName','x',           'Label','',   'Mapping',{'lin', -2, 2}),...
            audioPluginParameter('yDim',            'DisplayName','y',           'Label','',   'Mapping',{'lin', -2, 2}),...
            audioPluginParameter('zDim',            'DisplayName','z',           'Label','',   'Mapping',{'lin', -2, 2}),...
            audioPluginParameter('extend',          'DisplayName','Extend (x2)', 'Label','',   'Mapping',{'enum', 'Off', 'On'}),...
            audioPluginParameter('strength',        'DisplayName','Strength',    'Label','',   'Mapping',{'lin', 0, 1}),...           
            audioPluginParameter('gainCompensation','DisplayName','Auto Gain',   'Label','',   'Mapping',{'enum', 'Off', 'On'}),...          
            audioPluginParameter('inputGain',       'DisplayName','In Gain',     'Label','dB', 'Mapping',{'pow', 1/3, -80, 12}),...
            audioPluginParameter('outputGain',      'DisplayName','Out Gain',    'Label','dB', 'Mapping',{'pow', 1/3, -80, 12}));
        
    else 
    
        PluginInterface = audioPluginInterface(...
            'InputChannels',2,...
            'OutputChannels',2,...
            'PluginName','flowEQ',...
            'VendorName','Christian Steinmetz',...
            'VendorVersion',vendorVersion,...
            ... % Model Parameters
            audioPluginParameter('latentDim',       'DisplayName','Latent',            'Label','',   'Mapping',{'enum','1','2','3'}),...
            audioPluginParameter('eqMode',          'DisplayName','EQ Mode',           'Label','',   'Mapping',{'enum', 'Traverse','Semantic','Manual'}),...
            audioPluginParameter('xDim',            'DisplayName','x',                 'Label','',   'Mapping',{'lin', -2, 2}),...
            audioPluginParameter('yDim',            'DisplayName','y',                 'Label','',   'Mapping',{'lin', -2, 2}),...
            audioPluginParameter('zDim',            'DisplayName','z',                 'Label','',   'Mapping',{'lin', -2, 2}),...
            audioPluginParameter('extend',          'DisplayName','Extend (x2)',       'Label','',   'Mapping',{'enum', 'Off', 'On'}),...
            audioPluginParameter('firstCode',       'DisplayName','Embedding A',       'Label','',   'Mapping',{'enum', 'Warm','Warmer','Warmest','Bright','Brighter','Brightest'}),...
            audioPluginParameter('secondCode',      'DisplayName','Embedding B',       'Label','',   'Mapping',{'enum', 'Warm','Warmer','Warmest','Bright','Brighter','Brightest'}),...
            audioPluginParameter('interpolate',     'DisplayName','Interpolate',       'Label','',   'Mapping',{'lin', 0, 1}),...
            audioPluginParameter('disentanglement', 'DisplayName','Beta',              'Label','',   'Mapping',{'enum', 'None','Less', 'Some', 'More'}),...
            audioPluginParameter('strength',        'DisplayName','Strength',          'Label','',   'Mapping',{'lin', 0, 1}),...           
            audioPluginParameter('gainUpdateRate',  'DisplayName','Update Rate',       'Label','',   'Mapping',{'enum', 'Fast','Med.','Slow'}),...          
            audioPluginParameter('gainRange',       'DisplayName','Gain Range',        'Label','',   'Mapping',{'enum', '6dB','12dB','24dB'}),...          
            audioPluginParameter('gainCompensation','DisplayName','Auto Gain Comp.',   'Label','',   'Mapping',{'enum', 'Off', 'On'}),...          
            audioPluginParameter('inputGain',       'DisplayName','In Gain',           'Label','dB', 'Mapping',{'pow', 1/3, -80, 12}),...
            audioPluginParameter('outputGain',      'DisplayName','Out Gain',          'Label','dB', 'Mapping',{'pow', 1/3, -80, 12}),...
            ... % Parametric EQ Parameters 
            audioPluginParameter('lowShelfActive',  'DisplayName','Active',            'Label','',   'Mapping',{'enum', 'Bypassed','Active'}),...
            audioPluginParameter('lowShelfGain',    'DisplayName','Lowshelf Gain',     'Label','dB', 'Mapping',{'lin', -12, 12}),...
            audioPluginParameter('lowShelfFreq',    'DisplayName','Lowshelf Freq.',    'Label','Hz', 'Mapping',{'lin', 22, 1000}),...
            audioPluginParameter('firstBandActive', 'DisplayName','Active',            'Label','',   'Mapping',{'enum', 'Bypassed','Active'}),...
            audioPluginParameter('firstBandGain',   'DisplayName','First Band Gain',   'Label','dB', 'Mapping',{'lin', -12, 12}),...
            audioPluginParameter('firstBandFreq',   'DisplayName','First Band Freq.',  'Label','Hz', 'Mapping',{'lin', 82, 3900}),...
            audioPluginParameter('firstBandQ',      'DisplayName','First Band Q',      'Label','',   'Mapping',{'lin', 0.1, 10}),...
            audioPluginParameter('secondBandActive','DisplayName','Active',            'Label','',   'Mapping',{'enum', 'Bypassed','Active'}),...
            audioPluginParameter('secondBandGain',  'DisplayName','Second Band Gain',  'Label','dB', 'Mapping',{'lin', -12, 12}),...
            audioPluginParameter('secondBandFreq',  'DisplayName','Second Band Freq.', 'Label','Hz', 'Mapping',{'lin', 180, 4700}),...
            audioPluginParameter('secondBandQ',     'DisplayName','Second Band Q',     'Label','',   'Mapping',{'lin', 0.1, 10}),...
            audioPluginParameter('thirdBandActive', 'DisplayName','Active',            'Label','',   'Mapping',{'enum', 'Bypassed','Active'}),...
            audioPluginParameter('thirdBandGain',   'DisplayName','Third Band Gain',   'Label','dB', 'Mapping',{'lin', -12, 12}),...
            audioPluginParameter('thirdBandFreq',   'DisplayName','Third Band Freq.',  'Label','Hz', 'Mapping',{'lin', 220, 10000}),...
            audioPluginParameter('thirdBandQ',      'DisplayName','Third Band Q',      'Label','',   'Mapping',{'lin', 0.1, 10}),...
            audioPluginParameter('highShelfActive', 'DisplayName','Active',            'Label','',   'Mapping',{'enum', 'Bypassed','Active'}),...
            audioPluginParameter('highShelfGain',   'DisplayName','Highshelf Gain',    'Label','dB', 'Mapping',{'lin', -12, 12}),... 
            audioPluginParameter('highShelfFreq',   'DisplayName','Highshelf Freq.',   'Label','Hz', 'Mapping',{'lin', 580, 20000}));
    end
end
end