function SaveLatentCodes(filename)
% SAVELATENTCODES Load .mat file with the embeddings for each of the
% semantic descriptors. This file is generated by the Python script.
%
%   This may be removed shortly by simply creating the .mat file in Python.

latentCodes1d = {...
     [ 0.2],... % warm
	 [-0.2],... % bright
	 [-1.2]};   % sharp

latentCodes2d = {...
     [ 0.2  0.1],... % warm
	 [-0.2  0.5],... % bright
	 [-1.2  1.2]};   % sharp

latentCodes3d = {...
     [ 0.2  0.1  1.2],... % warm
	 [-0.2  0.5 -2.1],... % bright
	 [-1.2  1.2  0.1]};   % sharp

codes = {latentCodes1d, latentCodes2d, latentCodes3d};


save('assets/codes.mat', 'codes')